var javaScript = [
    {
        "question": "Which of the following is not a JavaScript data type?",
        "answer": "True",
        "choice1": "Number",
        "choice2": "String",
        "choice3": "Boolean",
    },
    {
        "question": "Which of the following is not a JavaScript variable declaration?",
        "answer": "div",
        "choice1": "var",
        "choice2": "let",
        "choice3": "const",
    },
    {
        "question": "Which of the following JavaScript variable declaration has a global scope?",
        "answer": "var",
        "choice1": "let",
        "choice2": "const",
        "choice3": "function",
    },
    {
        "question": "Which of the following JavaScript variable declarations has a block scope?",
        "answer": "let",
        "choice1": "var",
        "choice2": "function",
        "choice3": "num",
    },
    {
        "question": "Which of the following is an increment operator in JavaScript?",
        "answer": "++",
        "choice1": "--",
        "choice2": "//",
        "choice3": "&&",
    },
    {
        "question": "How do you begin a single line comment in JavaScript?",
        "answer": "//",
        "choice1": "<!--",
        "choice2": "#",
        "choice3": "%",
    },
    {
        "question": "Which of the following is not a logical operator in JavaScript?",
        "answer": '"\xa0\xa0"',
        "choice1": "&&",
        "choice2": "||",
        "choice3": "!",
    },
    {
        "question": "What is the AND logical operator in JavaScript?",
        "answer": "&&",
        "choice1": "||",
        "choice2": "!",
        "choice3": '"\xa0\xa0"',
    },
    {
        "question": "What is the OR logical operator in JavaScript?",
        "answer": "||",
        "choice1": "&&",
        "choice2": "!",
        "choice3": '"\xa0\xa0"',
    },
    {
        "question": "What is the NOT logical operator in JavaScript?",
        "answer": "!",
        "choice1": "&&",
        "choice2": "||",
        "choice3": '"\xa0\xa0"',
    },
    {
        "question": "Which of the following is a correctly defined JavaScript function?",
        "answer": "function myFunction()",
        "choice1": "function myFunction[]",
        "choice2": "function myFunction{}",
        "choice3": "function == myFunction()",
    },
    {
        "question": "Inside which HTML element do we put the script?",
        "answer": "<script>",
        "choice1": "<js>",
        "choice2": "<javascript>",
        "choice3": "<body>",
    },
    {
        "question": "What is the correct syntax for linking an external JavaScript file?",
        "answer": '<script src="xxx.js">',
        "choice1": '<script href="xxx.js">',
        "choice2": '<script alt="xxx.js">',
        "choice3": 'getElement("xxx.js")',
    },
    {
        "question": "How do you call a function named myFunction?",
        "answer": "myFunction()",
        "choice1": "call myFunction()",
        "choice2": "alert(myFunction)",
        "choice3": "getElement(myFunction)",
    },
    {
        "question": "What is the index number of the first element in a JavaScript array?",
        "answer": "0",
        "choice1": "1",
        "choice2": "2",
        "choice3": "3",
    },
    {
        "question": "Which of the following is a correct JavaScript array?",
        "answer": 'var classmates = ["Bob","Jane","Mary"]',
        "choice1": 'var classmates = {"Bob","Jane","Mary"}',
        "choice2": 'var classmates = ("Bob","Jane","Mary")',
        "choice3": 'var classmates = [1:"Bob",2:"Jane",3:"Mary"]',
    }, 
    {
        "question": "How do you return the number of elements in a JavaScript array?",
        "answer": "array.length",
        "choice1": "array.numberElements",
        "choice2": "array.getLength",
        "choice3": "array(totalElements)",
    }
]

var python = [
    {
        "question": "Which of the following is the correct syntax for a python if statement?",
        "answer": "",
        "choice1": "",
        "choice2": "",
        "choice3": "",
    },
    // {
    //     "question": "Which of the following is a correct Python array?",
    //     "answer": 'colors = ("blue", "red", "green")',
    //     "choice1": 'var classmates = {"blue","red","green"}',
    //     "choice2": 'var classmates = ["blue","red","green"]',
    //     "choice3": 'var classmates = [1:"blue",2:"red",3:"green"]',
    // },
    {
        "question": "How do you allow a user to enter a value that is stored as a string in Python?",
        "answer": 'input("Enter a value: ")',
        "choice1": 'cin("Enter a value: ")',
        "choice2": 'insert("Enter a value: ")',
        "choice3": 'prompt("Enter a value: ")',
    },
    {
        "question": 'How do you output "Hello World" to the user in Python?',
        "answer": 'print("Hello World")',
        "choice1": 'output("Hello World")',
        "choice2": 'display("Hello World")',
        "choice3": 'cout("Hello World")',
    },
    {
        "question": "?",
        "answer": "",
        "choice1": "",
        "choice2": "",
        "choice3": "",
    },
    {
        "question": "How do you begin a single line comment in Python?",
        "answer": "#",
        "choice1": "<!--",
        "choice2": "//",
        "choice3": "%",
    },
    {
        "question": "",
        "answer": "",
        "choice1": "",
        "choice2": "",
        "choice3": "",
    },
    {
        "question": "?",
        "answer": "",
        "choice1": "",
        "choice2": "",
        "choice3": "",
    },
    {
        "question": "?",
        "answer": "",
        "choice1": "",
        "choice2": "",
        "choice3": "",
    },
    {
        "question": "?",
        "answer": "",
        "choice1": "",
        "choice2": "",
        "choice3": "",
    },
    {
        "question": "PYTHON Which of the following is a correctly defined JavaScript function?",
        "answer": "function myFunction()",
        "choice1": "function myFunction[]",
        "choice2": "function myFunction{}",
        "choice3": "function == myFunction()",
    },
    {
        "question": "PYTHON Inside which HTML element do we put the script?",
        "answer": "<script>",
        "choice1": "<js>",
        "choice2": "<javascript>",
        "choice3": "<body>",
    },
    {
        "question": "PYTHON What is the correct syntax for linking an external JavaScript file?",
        "answer": '<script src="xxx.js">',
        "choice1": '<script href="xxx.js">',
        "choice2": '<script alt="xxx.js">',
        "choice3": 'getElement("xxx.js")',
    },
    {
        "question": "PYTHON How do you call a function named myFunction?",
        "answer": "myFunction()",
        "choice1": "call myFunction()",
        "choice2": "alert(myFunction)",
        "choice3": "getElement(myFunction)",
    },
    {
        "question": "What is the index number of the first element in a Python array?",
        "answer": "0",
        "choice1": "1",
        "choice2": "2",
        "choice3": "3",
    },
    {
        "question": "PYTHON Which of the following is a correct JavaScript array?",
        "answer": 'var classmates = ["Bob","Jane","Mary"]',
        "choice1": 'var classmates = {"Bob","Jane","Mary"}',
        "choice2": 'var classmates = ("Bob","Jane","Mary")',
        "choice3": 'var classmates = [1:"Bob",2:"Jane",3:"Mary"]',
    }, 
    {
        "question": "How do you return the number of elements in a Python list?",
        "answer": "len(listName)",
        "choice1": "listName.numberElements",
        "choice2": "listName.length",
        "choice3": "listName(totalElements)",
    }
]